replicaCount: 1

image:
  repository: siddharth67/block-buster-dev:7.5.0
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  nodePort: 30007
  port: 80
  targetPort: 80

namespace:
  name: 5-demo

labels:
  app:
    name: bb-app
    version: 7.5.0
    env: uat
