---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAG42S75E1Lg+p+f0AkA8AbgxAsulPKdZlpsDb+C3a/+1IJwZFOwzda7dRMvC8JI28VC6itbL5Psiv4RhFIinTbiAObF0ZuJcoSRivhwEKzCFHKipLB4LLSIZ0d75/xYOtAs8ZOlOw4aSV2FrtVdiY/gLoMPyAhrSjWyFnx2dyI4Y95b79WlnmU663LzUwpciPw4KGqbsq5nnNqtl0qT5sQOPz0vw8EJbJXTI4eps2TRPYBKc9CAqZbBcHJCdHsbjJVjnh4mfpBiZwPMDc96/TR/4rv1NeCt8CPcSN+A4XknjMAORQ+6PkbT+AKWHA4zcu3tTCz+GsB9A9KQlE/QGAGsFHFscNd2ASxOlcnvtoYr4vtvIervqse96ldoKt7z4uzkt+k2aLxaYafstzU9DPx6zahoK+VRPaow1YleJnCtRTBW626tMPzMIDebmZeliRBIwycOBEJFpfrvOLme77YXm8OCamcY/F9tg2uQAC9dAMBjcWLmN2e678jil/mvfdCvIATS/Z0AWOoD3SuENWJaSOz/lo7Q0kF56D3WKb/KfQAGtRsi1uRotfOrC+UKUmNtvtXTscT+jPFYyWQ/4+gdgn8TtmF1bECHzFOXP+8G7wGsY+q5FYlgT4crpGAZfBL3S1DtJO4BKb3sAEU9vvQ0KUh9ns6tcLCY+AweNwThBOH65Xm2QbuNYnzcIhNAUpDIeMO/XIQ7orqZ1SijLsSIj2CsVVr+6xT
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
